[tmdb]
api_key = "your-default-key-here"

[jellyseerr]
api_key = "your-default-key-here"
url = "http://localhost:5055"

[server]
host = "0.0.0.0"
port = 3000

[rate_limit]
requests_per_second = 10
burst_size = 20
